<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVosnxDr\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVosnxDr/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerVosnxDr.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerVosnxDr\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerVosnxDr\App_KernelDevDebugContainer([
    'container.build_hash' => 'VosnxDr',
    'container.build_id' => '52cd8511',
    'container.build_time' => 1654201158,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerVosnxDr');
